name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Update and Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-utils
        sudo apt-get install -y --no-install-recommends sudo ca-certificates pkg-config curl wget bzip2 xz-utils make git bsdtar doxygen gnupg unzip
        sudo apt-get clean
        
    - name: Install devkitPro
      run: |
        wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
        sudo dpkg -i devkitpro-pacman.deb
        rm devkitpro-pacman.deb
        sudo dkp-pacman -Scc --noconfirm
        
    - name: Install Devkits
      run: |
        sudo dkp-pacman -Syyu --noconfirm switch-dev
        sudo dkp-pacman -Syyu --noconfirm 3ds-dev
        sudo dkp-pacman -Syyu --noconfirm devkitARM
        sudo dkp-pacman -Syyu --noconfirm devkitPPC
        sudo dkp-pacman -Syyu --noconfirm wut
        sudo dkp-pacman -Syyu --noconfirm wii-dev
        sudo dkp-pacman -Scc --noconfirm
    
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Build
      env:
        DEVKITPRO: /opt/devkitpro
        DEVKITARM: /opt/devkitpro/devkitARM
        DEVKITPPC: /opt/devkitpro/devkitPPC
        WUT_ROOT: /opt/devkitpro/wut
      run: make
